[package]
name = "macro-test-helpers"
version = "0.1.0"
authors = ["Pieter <github@chesedo.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "0.6"